server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:ever0o/cloudLearn-config.git
          uri: https://github.com/ever0o/cloudLearn-config.git
          search-paths:
            - cloudLearn-config
          username: ever0o
          password: wy19920526

      label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka