server:
  port: 80
spring:
  application:
    name: cloud-cosumer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicodetrue&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

