server:
  port: 8003
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicodetrue&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
  cloud:
    zookeeper:
      connect-string: localhost:2181


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ever.springcloud.entitys
